apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
  namespace: quiz
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - image: vital7b/user-service:V1
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: "700Mi"
              cpu: "250m"
            limits:
              memory: "750Mi"
              cpu: "500m"
          imagePullPolicy: Always
          name: user
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: quiz
  labels:
    app: user-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "5001"
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 5001
  type: NodePort
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: user-service-hpa
#   labels:
#     app: user
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: user-depl
#   minReplicas: 1
#   maxReplicas: 2
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 80
