apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-depl
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      hostNetwork: true
      containers:
        - image: vital7b/gateway:V1
          ports:
            - containerPort: 7000
          imagePullPolicy: Always
          name: gateway
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: LoadBalancer
