apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-depl
  labels:
    app: domain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: domain
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: domain
    spec:
      hostNetwork: true
      containers:
        - image: vital7b/domain-service:V1
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          name: domain
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  

---
apiVersion: v1
kind: Service
metadata:
  name: domain-service
spec:
  selector:
    app: domain
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP



