server:
  port: 7000

spring:
  cloud:
    gateway:
      routes:
        - id: domains-service
          uri: http://localhost:5000/domains
          predicates:
            - Path=/domains/**
        - id: session-service
          uri: http://localhost:5001/session
          predicates:
            - Path=/session/**
            - Method=GET
          filters:
            - name: RewritePath
              args:
                regex: "/session/(?<remaining>.*)"
                replacement: "/blocked"
        - id: session-aggregator
          uri: http://localhost:6000/session-aggregator
          predicates:
            - Path=/session-aggregator/**
