apiVersion: apps/v1
kind: Deployment
metadata:
  name: setting-depl
  labels:
    app: setting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: setting
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: setting
    spec:
      hostNetwork: true
      containers:
        - image: vital7b/setting-service:V1
          ports:
            - containerPort: 5005
          imagePullPolicy: Always
          name: setting
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: setting-service
spec:
  selector:
    app: setting
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
  type: ClusterIP
