apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-depl
  namespace: quiz
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: test
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "actuator/prometheus"
        prometheus.io/port: "5004"
    spec:
      containers:
        - image: vital7b/test-service:V1
          imagePullPolicy: Always
          name: test
          ports:
            - containerPort: 5004
          resources:
            requests:
              memory: "800Mi"
              cpu: "500m"
            limits:
              memory: "1000Mi"
              cpu: "1200m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 5004
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 5004
            initialDelaySeconds: 15
            periodSeconds: 5
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: quiz
spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      name: http-traffic
      port: 6004
      targetPort: 5004
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-hpa
  namespace: quiz
  labels:
    app: test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-depl
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
