apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-depl
  labels:
    app: session
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: session
    spec:
      hostNetwork: true
      containers:
        - image: vital7b/session-service:V1
          ports:
            - containerPort: 5001
          imagePullPolicy: IfNotPresent
          name: session
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  

---
apiVersion: v1
kind: Service
metadata:
  name: session-service
spec:
  selector:
    app: session
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer



