apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-depl
  labels:
    app: course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: course
    spec:
      hostNetwork: true
      containers:
        - image: vital7b/course-service:V1
          ports:
            - containerPort: 5003
          imagePullPolicy: Always
          name: course
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  selector:
    app: course
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP
