apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-aggregator-depl
  labels:
    app: session-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-aggregator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: session-aggregator
    spec:
      hostNetwork: true
      containers:
        - image: vital7b/session-aggregator:V1
          ports:
            - containerPort: 6000
          imagePullPolicy: Always
          name: session
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: session-aggregator
spec:
  selector:
    app: session-aggregator
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: ClusterIP
